# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_name', models.CharField(max_length=100)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binomial_name', models.CharField(max_length=200)),
                ('indian_name', models.CharField(max_length=200)),
                ('image_url', models.URLField(default=b'https://www.ikea.com/PIAimages/0614197_PE686822_S5.JPG')),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=b'New Category', on_delete=django.db.models.deletion.CASCADE, to='Plants.Categories')),
            ],
        ),
    ]
