# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(default=b'https://www.ikea.com/PIAimages/0614197_PE686822_S5.JPG'),
        ),
    ]
